services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: application
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=lmfrotas
      - DB_USERNAME=user
      - DB_PASSWORD=secret
    networks:
      - lmfrotas

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lmfrotas

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: lmfrotas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lmfrotas

volumes:
  postgres_data:
    driver: local

networks:
  lmfrotas:
    driver: bridge